### ISSUE TITLE
Taxes not updated reactively - need GraphQL subscription

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/example-storefront#469] opened 2019-01-03 09:38 UTC
Type: **major**

**Describe the bug**
When changing the quantity of the items or shipping address, the tax calculated is not updated reactively, the page has to be refreshed to get the taxes.

**To Reproduce**
1. Go to Admin, enable "Example tax service"
2. Create a new product.
3. Add it to the cart, go to the checkout page, see that taxes are caclulated.
4. Change the quantity of the item. See that taxes are not updated.
5. Refresh the page, see that taxes are now updated.

**Expected behavior**
The taxes should be updated reactively.

**Comment by aldeed** [comment] 2019-01-07 21:11
I noticed this when I was testing, too, but there isn't any easy solution. The recalc happens async on the server, so the response doesn't have the updates. The next response usually does, but then it doesn't have _those_ updates. So it's essentially always one change behind.

The proper solution is to use a GraphQL subscription for part of cart. We were waiting to introduce subscriptions until we had a use case, and this might be a good test case.

**Comment by zenweasel** [comment] 2019-03-01 08:09
@aldeed @kieckhafer Testing checkout today it appears that this is still not working. Is there any status update on this?

**Comment by spencern** [comment] 2019-03-04 22:13
@kkuzemka @kieckhafer do either of you know if/who picked this up?

**Comment by kieckhafer** [comment] 2019-03-04 22:17
@zenweasel is this not working for you here in this repo? or in another location? It is (or at least was) fixed in a non-subscription manner, and this was left open to deal with subscriptions in the future.

**Comment by zenweasel** [comment] 2019-03-04 22:21
I included reproduction steps in the slack message as it includes non-public URL's

**Comment by aldeed** [comment] 2019-03-05 17:30
The previous "solution" was based on re-finding the doc that is returned from a mutation after events are emitted and awaited. I think we only did this in one mutation, so I would look specifically into which mutations are getting called to update the cart. Maybe other mutations need the same kind of change.

But without subs, we’re only buying time. Subs are the correct solution but ideally we should figure out a better pubsub provider first (which logically would be Kafka since we already require it now).

A middle-ground workaround for now would be to set `pollInterval={10}` on the `Query` components where this is an issue (10-second polling). API will be hit a lot of unnecessary times, but it will get the job done.

Or similarly, we could add some code in the UI that does a single re-fetch 5 seconds after each cart mutation.

**Comment by spencern** [comment] 2019-03-08 20:58
@rosshadden can we close this now? Or do we need to merge/migrate your changes into this repo?

**Comment by janus-reith** [comment] 2019-03-29 13:48
Has there been any further work to actually use subscriptions beside the `<SubscriptionTest />` component? @aldeed Why would Kafka be necessary for this? What would be the caveats when using GraphQL subscriptions directly with Node + MongoDB, where would Kafka come into play and what would it solve?

I'd really be interested to gain more insights into your current roadmap.

**Comment by zenweasel** [comment] 2019-04-01 07:32
@rosshadden  Second call to close or update this ticket. It's been 3 weeks since the last update

**Comment by rosshadden** [comment] 2019-04-01 15:08
My changes were not in this project. I can try porting them over here, but would need the find time to test it.

**Comment by aldeed** [comment] 2019-04-02 20:33
@janus-reith On the server side, it is hard coded to use an `apollo-server` `PubSub` instance: https://github.com/reactioncommerce/reaction/blob/develop/imports/node-app/core/ReactionNodeApp.js#L36-L39

But Apollo folks do not recommend using it for production. I'm not sure it will work correctly for installations running multiple instances of the server. Using Kafka would solve this, or at a bare minimum it should be possible for a plugin to override the pub sub provider.

**Comment by janus-reith** [comment] 2019-04-04 16:20
Thank you, now I get it.

**Closed** 2021-11-16 19:55 UTC
Labels: bug
