### ISSUE TITLE
infinite loader if the payment is rejected

### ISSUE THREAD

**Issue by CristianCucunuba** [reactioncommerce/example-storefront#699] opened 2020-07-10 00:02 UTC
Type: **minor**

**Describe the bug**
When you are placing and order on the checkout, using X payment gateway, If the payment is reject or fails the loader waiting for the order to place, never stops and we can't notifying the user that the payment failed.

**To Reproduce**
1. Add a product to the cart
2. Go to the checkout and fill step 1 and 2
3. Select your payment method and make sure it fails, for example entering a wrong credit card number if you use stripe
4. Place the order
5. See the infinite loader

**Expected behavior**
Stop the loader and display the alert with the error. CheckoutActions already do that but [this](https://github.com/reactioncommerce/example-storefront/blob/bad4cce75be188de7bcda4c894351e2db592dbe6/components/CheckoutActions/CheckoutActions.js#L219) conditional is not letting the component set the alert. For some reason the component is already unmounted and the component can't update the state

**Screenshots**
![image](https://user-images.githubusercontent.com/8785633/87101738-7f0ece80-c215-11ea-8d2c-0b77071bfff3.png)

**Comment by janus-reith** [comment] 2020-07-10 07:50
@CristianCucunuba Thanks for filing the issue!
Could you add which branch/version you use while observing that issue?

It seems like you spotted the right place, as due to my latest changes, `this._isMounted` is not set to true in the first place:
https://github.com/reactioncommerce/example-storefront/commit/0ae583eb5f3f7a96270d968b536c770773a3cc38#diff-9b6019bce1be1df5431a56f4a139663dL77
Fixing this right away.

However, as this should not be present in the latest v3.1.0 stable release, I'd like to clarify if you might have encountered some other issue, where the component might actually not be mounted.

**Comment by CristianCucunuba** [comment] 2020-07-10 15:43
I'm using v3.1.0/trunk, at the moment I haven't seen other issue with the component

**Comment by janus-reith** [comment] 2020-07-14 19:54
Closing this now that #700 is merged and @manueldelreal confirmed that showing an error message works.
(Further context: Usually I would leave this open until the fix landed in a release, but this error should only occur in trunk but not the latest stable v3.1.0)

**Closed as completed by janus-reith** 2020-07-14 19:54 UTC
